SELECT C.ANIMAL_ID,
       C.NAME
FROM (SELECT A.ANIMAL_ID,
             A.NAME,
             DATEDIFF(A.DATETIME, B.DATETIME) AS DAYS
      FROM ANIMAL_OUTS A
      LEFT OUTER JOIN ANIMAL_INS B
      ON A.ANIMAL_ID = B.ANIMAL_ID
      ORDER BY DAYS DESC) AS C
LIMIT 2
