SELECT B.ID,
CASE
       WHEN B.LEVEL = 1 THEN 'CRITICAL'
       WHEN B.LEVEL = 2 THEN 'HIGH'
       WHEN B.LEVEL = 3 THEN 'MEDIUM'
       ELSE 'LOW'
       END AS 'COLONY_NAME'
FROM (SELECT ID, NTILE(4)
      OVER(ORDER BY SIZE_OF_COLONY DESC) AS 'LEVEL'
      FROM ECOLI_DATA) AS B
      ORDER BY B.ID