SELECT APNT_NO,
       PT_NAME,
       A.PT_NO,
       B.MCDP_CD,
       DR_NAME,
       APNT_YMD
FROM PATIENT A, DOCTOR B, APPOINTMENT C
WHERE A.PT_NO = C.PT_NO
AND B.DR_ID = C.MDDR_ID
AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND APNT_CNCL_YN = 'N'
AND B.MCDP_CD = 'CS'
ORDER BY APNT_YMD