-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE,
       E.EMP_NO,
       E.EMP_NAME,
       E.POSITION,
       E.EMAIL
FROM HR_EMPLOYEES E, HR_GRADE G
WHERE G.EMP_NO = E.EMP_NO
AND G.YEAR = 2022
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
